### ISSUE TITLE
Suggestions do not appear for global variables

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/plugin-intellij#309]
When global variables are declared and those are used later inside functions, suggestions does not appear for them.

**Comment by Shan1024** [comment]
@erandidesilva: Could not reproduce this issue on my side. Would you be able to post an example which I could use to reproduce this issue?

**Comment by Shan1024** [comment]
Seems like the @erandidesilva was using plugin v0.8.4 which did not support global variables. Updating to plugin v0.8.5 fixed this issue.
