### ISSUE TITLE
Suggestions are not appearing when associated with structs

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/plugin-intellij#332]
Steps
1. Define a struct inside a function
2. The definitions used inside the struct does not appear as suggestions when trying to access the struct.

Example:
` struct Department {
        string dptName;
        Person[] employees;
    }`

Later when using Department or deptName associated suggestions are not coming

**Comment by Shan1024** [comment]
Resolved in https://github.com/ballerinalang/plugin-intellij/pull/469.
