### ISSUE TITLE
Typos for some keywords

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/plugin-intellij#345]
![typo2](https://cloud.githubusercontent.com/assets/1845370/26626272/577cd07c-4614-11e7-9c45-0379c93d69a5.png)

![typo](https://cloud.githubusercontent.com/assets/1845370/26626271/57771e98-4614-11e7-8c89-f084387f30fb.png)

**Comment by Shan1024** [comment]
@dilinisg: Some words like are not available in the IDEA dictionary and hence it shows the error of **Type in word**. Please note that the words are case sensitive. If we use `LinkedIn` instead of  `linkedin`, it will not show the warning.

**Comment by dilinisg** [comment]
@Shan1024 - We cannot use "LinkedIn" as the connector implementation has defined it as "linkedin"

**Comment by Shan1024** [comment]
@dilinisg: I was just giving an example :) Anyway, if you want to remove the message, you can add these words to the dictionary by right clicking in the word. After that, this message will not be displayed.
