### ISSUE TITLE
When auto generating the join syntax, message[] should be changed to map

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/plugin-intellij#454]
When auto generating the join syntax in fork-join, message[] should be changed to map as only map is supported

```
        fork{

        }join () (message[] ) {
            
        }
```

**Comment by Shan1024** [comment]
This is already fixed in https://github.com/ballerinalang/plugin-intellij/commit/b4cf7fd2f0daed3fb119580b0537e5954153c445.
