### ISSUE TITLE
The map variable does not auto populate inside the join block

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/plugin-intellij#455]
The map variable (joinMsg in this example) does not auto populate inside the join block

```
join (all) (map joinMsg) {
          messages:setStringPayload(result, joinMsg);
}
```

**Comment by Shan1024** [comment]
Duplicate of https://github.com/ballerinalang/plugin-intellij/issues/399.

**Comment by Shan1024** [comment]
Fixed in https://github.com/ballerinalang/plugin-intellij/pull/469.
