### ISSUE TITLE
Code formatting shortcut messes the format

### ISSUE THREAD

**Issue by lahirus** [ballerinalang/plugin-intellij#465]
<img width="941" alt="screen shot 2017-07-01 at 1 06 05 pm" src="https://user-images.githubusercontent.com/3665108/27764402-2c46ed90-5e5e-11e7-9ffb-efce494c824d.png">

**Comment by Shan1024** [comment]
@lahirus : What is the plugin version you are using? Can you update it to the latest version? (0.8.8)

**Comment by lahirus** [comment]
Updating fixed the issue.
