### ISSUE TITLE
Doesn't detect duplicate variable names

### ISSUE THREAD

**Issue by pubudu91** [ballerinalang/plugin-intellij#479]
The plugin doesn't highlight when I declare a variable in the same name as in an existing one. 

```
files:File source = {path: "ftp://localhost/public/userA/aa.txt"};
files:File source = {path: "ftp://localhost/public/userB/mv.txt"};
```

**Comment by Shan1024** [comment]
This capability is to be provided by semantic analyzer. So marked as postponed.
