### ISSUE TITLE
Package import suggestions not working

### ISSUE THREAD

**Issue by pubudu91** [ballerinalang/plugin-intellij#482]
When moving the cursor to a package name we haven't imported (i.e: 'files' in the code snippet given below) and pressing Alt+Enter, it doesn't give us a list of suggested packages to import. 

```
files:File target = {path: "ftp://127.0.0.1/public/userB/mv.txt"};
```

**Comment by Shan1024** [comment]
@pubudu91 : Is the module is a Ballerina module and is there any syntax highlighting error(anywhere in the file) present at that moment?

**Comment by Shan1024** [comment]
Closing the issue since cannot reproduce.

**Comment by Shan1024** [comment]
Closing the issue since cannot reproduce.
