### ISSUE TITLE
Can we add installation and configuration instructions in intellij plugin page

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/plugin-intellij#516]
https://plugins.jetbrains.com/plugin/9520-ballerina

(1) How to install after downloading
(2) Do we have to configure SDK etc in intellij?

**Comment by Shan1024** [comment]
@uthaiyashankar You can directly install the plugin from the **Settings -> Plugins** in IDEA. I will add instructions to the readme.

SDK setup guide is already available at https://github.com/ballerinalang/plugin-intellij/tree/master/getting-started/setting-up-ballerina-sdk.
