### ISSUE TITLE
IDE reports problem with the plugin when starting up

### ISSUE THREAD

**Issue by pubudu91** [ballerinalang/plugin-intellij#521]
The IDE reported a problem with the plugin during startup and gave the 2 stacktraces attached. Not sure if the second one is of a different issue or a continuation of the first one. See the attached files. 

[ballerina-plugin-stacktrace-1.txt](https://github.com/ballerinalang/plugin-intellij/files/1168776/ballerina-plugin-stacktrace-1.txt)
[ballerina-plugin-stacktrace-2.txt](https://github.com/ballerinalang/plugin-intellij/files/1168775/ballerina-plugin-stacktrace-2.txt)

**Comment by Shan1024** [comment]
@pubudu91 : The implementation is changed with the v0.8.9 and this issue is fixed in the new version.
