### ISSUE TITLE
Some syntax errors are not highlighting

### ISSUE THREAD

**Issue by Shan1024** [ballerinalang/plugin-intellij#554]
Some syntax errors are not highlighting due to an issue in adaptor.

**Comment by dilinisg** [comment]
E.g.

![syntax1](https://user-images.githubusercontent.com/1845370/30467522-c1af0cf2-9a02-11e7-9191-5114ec307852.png)

**Comment by Shan1024** [comment]
This is fixed since the external annotator is added.
