### ISSUE TITLE
Name of service skeleton generated not compliant with the best practices guide

### ISSUE THREAD

**Issue by pubudu91** [ballerinalang/plugin-intellij#571]
As of now, the service skeleton generated by `New -> Ballerina File` is something like below:

```
package wirelog.http.services;

import ballerina.net.http;
import ballerina.lang.messages;

@http:configuration {basePath:"/hello"}
service<http> HelloService {

    @http:GET {}
    @http:Path {value:"/"}
    resource sayHello (message m) {
        message response = {};
        messages:setStringPayload(response, "Hello World !!!");
        reply response;
    }
}
```

The name of the service, "HelloService" is not compliant with Ballerina API guidelines and best practices. According to the guidelines, service names,
1. should be camel case
2. should not contain the term 'service'

It would be better if these program/service skeletons generated by the plugin adhere to the accepted guidelines and best practices.

**Comment by Shan1024** [comment]
@pubudu91 Implementing code inspections are on hold since we are planing to get all of the errors, warnings from the Ballerina semantic analyzer. Can you open an issue in the run-time repo to track this?
