### ISSUE TITLE
[Idea Plugin] Wrong validation is given for while loop

### ISSUE THREAD

**Issue by lankavitharana** [ballerinalang/plugin-intellij#577]
I have tried the following with the latest available idea plugin.

while(i != (noOfChildElements-1)){ index = string:valueOf(i+1); }

As shown in the image, its showing a validation error but this gets deployed in runtime without an error.
bug_ideaplugin_4

![caebbad2-e95d-11e6-830e-f5ce31b245ff](https://user-images.githubusercontent.com/6400879/29224707-1711fc48-7ee9-11e7-8d05-9683549a49c2.png)

**Comment by Shan1024** [comment]
The reason for this is an issue in grammar which we used at that time. Now this issue is fixed.
