### ISSUE TITLE
[Doc] Cannot find the idea plugin for latest released version 0.93

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/plugin-intellij#633]
I'm unable to find the compatible plugin for 0.93 release. https://plugins.jetbrains.com/plugin/9520-ballerina

**Comment by Shan1024** [comment]
Hi @yasassri,

The plugin version 0.9.1 support Ballerina 0.93. There was an oversight and the supporting Ballerina version was not added to the change log.
