### ISSUE TITLE
Plugin not getting listed under IntelliJ 2016.2 "Browse Repositories" window

### ISSUE THREAD

**Issue by shazni** [ballerinalang/plugin-intellij#634]
The README indicates the following IntelliJ versions have the plugin.

0.8.0 - 0.8.2 | IntelliJ IDEA 2016.3 - 2016.*
I have IntelliJ version 2016.2 in which the plugin is not getting listed under "Browse Repositories" window. 

If this version is not supported shall we remove 2016.* part, which kind of gives the impression that 2016.1 and 2016.2 etc are supported.

**Comment by Shan1024** [comment]
Hi @shazni,

 `2016.3 - 2016.*` was supposed to mean that all these plugins will support any 2016 IDEA version from 2016.3 to upward. I will specifically add that plugin does not support IDEA versions below 2016.3.
