### ISSUE TITLE
No auto completion available for `function`

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerinalang/plugin-intellij#642]
![auto_completion_func](https://user-images.githubusercontent.com/7592890/31541397-208bde78-b02c-11e7-81ef-8113bf94809f.png)

**Comment by Shan1024** [comment]
Hi @dilini-muthumala,

What is the plugin version you are using?

**Comment by dilini-muthumala** [comment]
Hi @Shan1024 , I am using plugin version 0.9.1

**Comment by Shan1024** [comment]
Hi @dilini-muthumala,

I could not reproduce this issue. Would you be able to provide a sample code where the auto completion is not working properly?

**Comment by dilini-muthumala** [comment]
Hi @Shan1024 ,

Please find the screenshot below:

![no-autocompletion](https://user-images.githubusercontent.com/7592890/31603758-c793008a-b27e-11e7-8efb-3bb0c5a07ea6.png)

Program is:
```
import ballerina.lang.system;

function main (string[] args) {
    system:println("test!");
}
```

when I type 'func', it does not give any suggestions.

**Comment by Shan1024** [comment]
Closing since cannot reproduce.
