### ISSUE TITLE
[Documentation] How to create a new Ballerina project in IntelliJ idea

### ISSUE THREAD

**Issue by SupunS** [ballerinalang/plugin-intellij#654]
Could not find any guidance on this in the docs. Found this blog [1] which has this information. IMO this should be in the docs.

This should be a subtask of https://github.com/ballerinalang/ballerina/issues/3549

[1] https://medium.com/@eranda.sooriyabandara/ballerina-language-setting-up-your-local-environment-intellij-idea-387c4d05e03f

**Comment by Shan1024** [comment]
Hi @SupunS,

This is already covered in https://github.com/ballerinalang/plugin-intellij/tree/master/getting-started/setting-up-ballerina-sdk.
