### ISSUE TITLE
[Documentation] How to install Ballerina plugin for IntelliJ idea?

### ISSUE THREAD

**Issue by SupunS** [ballerinalang/plugin-intellij#655]
Could not find any documentation on this. Found this information on a blog instead [1]

This will be a subtask of https://github.com/ballerinalang/ballerina/issues/3549

[1] https://medium.com/@eranda.sooriyabandara/ballerina-language-setting-up-your-local-environment-intellij-idea-387c4d05e03f

**Comment by Shan1024** [comment]
Hi @SupunS,

This is already covered in https://github.com/ballerinalang/plugin-intellij#installing-the-plugin-to-idea.
