### ISSUE TITLE
[Improvement] Provide a mechanism to create a ballerina package

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/plugin-intellij#701]
$subject please.

**Comment by Shan1024** [comment]
Hi @erandidesilva,

We can already create packages. Can you explain the problem you encountered?

**Comment by erandidesilva** [comment]
I have created the package structure using directory structure creation. This is on whether a package, which is similar to a java package can be created for Ballerina using IDEA.

**Comment by Shan1024** [comment]
This support is already there. Please try by creating a new Ballerina project.

![workspace 1_306](https://user-images.githubusercontent.com/4003115/32657119-92cec3e6-c63a-11e7-9bf9-a5ded39fa7cf.png)
