### ISSUE TITLE
Syntax highlighting issues: identifier names

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/plugin-intellij#703]
![80](https://user-images.githubusercontent.com/1845370/32657251-157e905a-c63b-11e7-9f5a-2a92b16140a8.png)

**Comment by Shan1024** [comment]
Hi @dilinisg,

What seems to be the issue here?

**Comment by dilinisg** [comment]
Color of the `er ` identifier is not same as other identifiers

**Comment by Shan1024** [comment]
Unused identifier will be colored in gray. That is why `ex` and `bal` are colored in gray. Used literal will have black or another respective color according to the type. That is why `er` is black.
