### ISSUE TITLE
Missing semi colon is not indicated as an error

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/plugin-intellij#715]
Currently when a statement is missing a semi colon, it's not indicated as wrong grammer. Composer provides this, hence will be useful to have it here as well.

**Comment by Shan1024** [comment]
@erandidesilva: When we missing a semicolon, error is shown in that line. Can you provide an example where it does not work as expected so I can find the issue?

**Comment by erandidesilva** [comment]
@Shan1024 
Please find the below. 

![issue_5](https://user-images.githubusercontent.com/15624590/33012665-9dfbfb6a-ce07-11e7-8ae6-258fffd105f7.png)

**Comment by Shan1024** [comment]
This is fixed since the external annotator is added.
