### ISSUE TITLE
Need to add support for passing program arguments for services

### ISSUE THREAD

**Issue by pubudu91** [ballerinalang/plugin-intellij#763]
Currently, you cannot pass program arguments when running Ballerina services. The user should be able to pass arguments to Ballerina services as well.

**Comment by Shan1024** [comment]
@pubudu91: In the earlier stages, arguments are not expected by Ballerina services run command. So we removed arguments adding support from service run configuration.

I just tried to run sample hello world service using the below command.

```
ballerina run /home/shan/Documents/WSO2/Sources/BallerinaByExamples/service.bal -s abc
```

But I get the following error.

```
ballerina: too many arguments
Run 'ballerina help' for usage.
``` 

Can you provide me an example where we need to add arguments when running services?

**Comment by pubudu91** [comment]
We need to pass an argument for example, when we want to enable HTTP trace logs.

**Comment by Shan1024** [comment]
Seems like we can only pass flags to services. 

Eg-
`-B[tracelog.http].level=TRACE`
