### ISSUE TITLE
Plugin does not indicate compilation error "variable assignment is required"

### ISSUE THREAD

**Issue by riyafa** [ballerinalang/plugin-intellij#784]
When the send method of `http:Response` is called without variable assignment as 
```response.send();``` a compilation error should be indicated by the plugin. Till we manually compile or run the plugin this error is not known.
Similar is the case when we call an http endpoint `httpEndpointA.get("/services/SimpleStockQuoteService", req);`. Hence it seems that the plugin does not recognize the "variable assignment is required" compilation error which has to be fixed.

**Comment by Shan1024** [comment]
@riyafa - What is the plugin version and Ballerina runtime version you are using?

**Comment by riyafa** [comment]
I updated to 0.9.8 release of the plugin and still have the issue. Ballerina version is 0.95.6

**Comment by Shan1024** [comment]
@Riyafa - Semantic analyzing support is added in plugin v0.9.8. So all errors are now getting highlighted properly. But you need to use 0.95.7 version with the plugin. Please test with the 0.95.7 version and let me know whether the error is getting highlighted properly.

**Comment by riyafa** [comment]
The same issue exists with Ballerina  0.95.7

**Comment by Shan1024** [comment]
I just double checked to make sure it works. Please refer the below screenshot.

![workspace 1_365](https://user-images.githubusercontent.com/4003115/34983218-d31478d4-fad2-11e7-9232-b39318708b1f.png)

Can you check again whether you have changed the both project SDK and module SDK to 0.95.7?

**Comment by riyafa** [comment]
Yes it seemed to have been fixed. The plugin is slow to display errors. Thanks anyway.
