### ISSUE TITLE
Plugin does not indicate compilation error "undefined symbol"

### ISSUE THREAD

**Issue by riyafa** [ballerinalang/plugin-intellij#785]
Say I use a variable `fullResponse` that is not declared anywhere the plugin does not indicate this error. Only after manually compiling the code that this error `undefined symbol` could be identified. 
For example I do not declare `fullResponse` but use it as follows:
![image](https://user-images.githubusercontent.com/8238078/34969653-d879ff16-fa95-11e7-9649-8d3f49be356d.png)
but no error is shown by the plugin.

**Comment by Shan1024** [comment]
@riyafa - What is the plugin version and Ballerina runtime version you are using?

**Comment by riyafa** [comment]
0.9.8 release of the plugin Ballerina version is 0.95.6

**Comment by Shan1024** [comment]
@riyafa - Semantic analyzing support is added in plugin v0.9.8. So all errors are now getting highlighted properly. But you need to use 0.95.7 version with the plugin. Please test with the 0.95.7 version and let me know whether the error is getting highlighted properly.

**Comment by riyafa** [comment]
The same issue exists with Ballerina  0.95.7

**Comment by Shan1024** [comment]
I just double checked to make sure it works. Please refer the below screenshot.

![workspace 1_364](https://user-images.githubusercontent.com/4003115/34983093-6532235c-fad2-11e7-8b4d-ff973d9f342d.png)

Can you check again whether you have changed the both project SDK and module SDK to 0.95.7?

**Comment by riyafa** [comment]
yes this also has been fixed.
